### ISSUE TITLE
How to redirect callr output while calling from future

### ISSUE THREAD

**Issue by 001ben** [HenrikBengtsson/future.callr#3]
I'm wondering if it's possible to pass an argument down to the underlying `callr::r` method when using the futures API.

Specifically, i want to make use of the `callr::r(show = TRUE)` argument, however i can't see any reference in the documentation to pass the parameter down.

P.S. the future-verse is amazing

**Comment by HenrikBengtsson** [comment]
Hi, sorry for the late reply.  

This feature request falls under the section of a "Extended/Optional Future API" discussed in https://github.com/HenrikBengtsson/future/issues/172.  The same wish for viewing output of parallel workers has been raised for other type of backends as well.

The key idea behind the Future API is that your future code (as a developer) should work regardless of which future backend is used (set by the _user_ via `plan()`.)  Because of this, it is important that future backends (such as future.callr) do not provide their own extensions/back doors to whatever underlying framework they're building upon.  In other words, what you're asking for needs to be defined via the Future API _that the future package defines_.   Exactly how these type of extended/optional features will be declared/provided is still to be decided, but it is on the road map.

The capturing of standard output (stdout) produced by a future is one of the first things that will be supported (hopefully already by one of the near future 'future' releases).  This will most likely not involve displaying output live, but rather displaying / making the output available when the future has resolved.  So, in the near term it will still not be possible to follow future evaluation live via output or progress bars.  Please feel free to continue this discussion over at https://github.com/HenrikBengtsson/future/issues/172 - any feedback and use cases will help identify what's needed.

**Comment by HenrikBengtsson** [comment]
... and thanks for the kind words :)

**Comment by 001ben** [comment]
Thanks for the reply, looking forward to extended future options :D
